spring:
  application:
    name: hyproj-ai
  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:7b
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.gptgod.online/
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    top.hyperplasma.hyprojai: debug