spring:
  profiles:
    active: dev
  application:
    name: hyproj-ai
  ai:
    openai:
      api-key: ${hyplus.api-key}
      base-url: ${hyplus.base-url}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    top.hyperplasma.hyprojai: debug