spring:
  application:
    name: hyproj-ai
  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:7b
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.gptgod.online/
      chat:
        options:
          # 请使用支持tool calling的模型
          model: gpt-4o-mini
          temperature: 0.7
  datasource:
    url: jdbc:sqlite:db/hyproj-ai.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:
logging:
  level:
    org.springframework.ai: debug
    top.hyperplasma.hyprojai: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.hyperplasma.hyprojai.entity.po